name: unet
channels:
  - conda-forge
  - pytorch
  - fastai
dependencies:
  - python==3.8.10
  - pip=21.1.2
  - numpy
  - pandas
  - tqdm
  - pytorch
  - torchvision
  - opencv-python-headless
  - pip:
      - Pillow
      - wandb
      - matplotlib
